name: Code quality

on: pull_request

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/ruff-action@v3
        
  ruff-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/ruff-action@v3
        with:
          args: format --check --diff

  ty-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          activate-environment: true
      
      - name: Install dependencies
        run: uv pip install -e .[dev]

      - name: Generate report
        run: uvx ty check .